# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-analytics

# Site settings
url: 'https://www.discoverspeyer.de'
baseurl: ''
title: 'Discover Speyer'
tagline: 'Revisit Speyer and see all the places you have visited!'
description: 'Website about Speyer. If you have joined my tour or plan to visit Speyer, this site provides you with all the information to get started!'
authro: 'Holger Bruchelt'
permalink: pretty
logo: "/images/Designer.png"
social: 
  twitter: 'https://x.com/hobru'
  instagram: 'https://www.instagram.com/walkingwithloki/'
  github: 'https://github.com/hobru'

# From https://github.com/hendrikschneider/jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-WHJKQYTCHT          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Not sure which was the right one, so I added both
# could probably also be added via https://github.com/daviddarnes/alembic?tab=readme-ov-file#site-before-starthtml--site-before-endhtml
google_analytics: 'G-WHJKQYTCHT'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Speyer
  url: /Speyer/
- title: Technikmuseum
  url: /Technikmuseum/
- title: Blog
  url: /blog/
- title: Impressum
  url: /impressum/
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""
    feature_text: |
    feature_image: "/images/Logo.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


